CONFIG = {
    "defaults": {
        "role_resumes": {
            "data engineer": "/absolute/path/to/data_engineer_resume.docx",
            "data scientist": "/absolute/path/to/data_scientist_resume.docx",
            "platform engineer": "/absolute/path/to/platform_engineer_resume.docx",
        },
        "user_data_dir": "/tmp/seekbot-chrome",
        "profile_directory": "Default",
        "compatibility_threshold": 5.0,
        "resume_switch_margin": 2.0,
        "max_pages": 3,
        "max_applications": 0,
    },
    "logging": {
        "run_log_path": "seekbot_run.log",
        "llm_log_path": "seekbot_llm.log",
        "debug_click_log_path": "seekbot_clicks.log",
        "csv_log_path": "seekbot_jobs.csv",
    },
    "llm": {
        "enabled": True,
        "provider": "ollama_client",
        "url": "http://localhost:11434/api/generate",
        "model": "gemma3",
        "temperature": 0.1,
        "timeout_s": 45,
        "cover_letter_signature_name": "Your Name",
    },
    "question_answers": {
        "location": "REPLACE_ME",
        "office_attendance": "REPLACE_ME",
        "previous_employer": "REPLACE_ME",
        "work_rights_statement": "REPLACE_ME",
        "work_authorization": "REPLACE_ME",
        "visa_type": "REPLACE_ME",
        "visa_expiry": "REPLACE_ME",
        "notice_period": "REPLACE_ME",
        "salary_expectation": "REPLACE_ME",
        "expected_daily_rate": "REPLACE_ME",
        "expected_hourly_rate": "REPLACE_ME",
        "drivers_license": "REPLACE_ME",
        "police_check_psychometric": "REPLACE_ME",
        "defence_clearance": "REPLACE_ME",
        "gender": "REPLACE_ME",
        "pronouns": "REPLACE_ME",
        "employee_referral": "REPLACE_ME",
        "work_rights": "REPLACE_ME",
        "reasonable_adjustments": "REPLACE_ME",
        "medical_conditions": "REPLACE_ME",
        "criminal_charge": "REPLACE_ME",
        "criminal_conviction": "REPLACE_ME",
        "referral_source": "REPLACE_ME",
        "consulting_experience": "REPLACE_ME",
        "years_data_analytics_consultant": "REPLACE_ME",
    },
}
