GLOBAL_MATCHING_TAXONOMY: list[tuple[str, list[str]]] = [
    ("python", [r"\bpython\b"]),
    ("sql", [r"\bsql\b"]),
    ("aws", [r"\baws\b", r"amazon web services"]),
    ("azure", [r"\bazure\b"]),
    ("azure devops", [r"azure devops"]),
    ("azure pipelines", [r"azure pipelines"]),
    ("gcp", [r"\bgcp\b", r"google cloud"]),
    ("databricks", [r"\bdatabricks\b"]),
    ("snowflake", [r"\bsnowflake\b"]),
    ("airflow", [r"\bairflow\b", r"apache airflow"]),
    ("dbt", [r"\bdbt\b"]),
    ("spark", [r"\bspark\b", r"apache spark"]),
    ("pyspark", [r"\bpyspark\b"]),
    ("kafka", [r"\bkafka\b"]),
    ("docker", [r"\bdocker\b"]),
    ("kubernetes", [r"\bkubernetes\b", r"\bk8s\b"]),
    ("terraform", [r"\bterraform\b"]),
    ("git", [r"\bgit\b", r"github", r"gitlab", r"\bbitbucket\b"]),
    ("ci/cd", [r"\bci/cd\b", r"\bcicd\b", r"continuous integration", r"continuous delivery"]),
    ("linux", [r"\blinux\b"]),
    ("etl", [r"\betl\b"]),
    ("elt", [r"\belt\b"]),
    ("data modeling", [r"data model", r"data modelling", r"dimensional model"]),
    ("data warehouse", [r"data warehouse", r"data warehousing", r"\bedw\b", r"enterprise data warehouse"]),
    ("data pipeline", [r"data pipeline", r"pipeline orchestration"]),
    ("streaming", [r"streaming", r"real[- ]time"]),
    ("machine learning", [r"machine learning", r"\bml\b"]),
    ("mlops", [r"\bmlops\b"]),
    ("data science", [r"data science", r"data scientist"]),
    ("data engineering", [r"data engineer", r"data engineering"]),
    ("ai", [r"\bai\b", r"artificial intelligence"]),
    ("llm", [r"\bllm\b", r"large language model", r"generative ai"]),
    ("tensorflow", [r"\btensorflow\b"]),
    ("pytorch", [r"\bpytorch\b"]),
    ("scikit-learn", [r"scikit[- ]learn", r"\bsklearn\b"]),
    ("pandas", [r"\bpandas\b"]),
    ("numpy", [r"\bnumpy\b"]),
    ("power bi", [r"power bi"]),
    ("power query", [r"power query"]),
    ("dax", [r"\bdax\b"]),
    ("tableau", [r"\btableau\b"]),
    ("power platform", [r"power platform"]),
    ("fabric", [r"microsoft fabric", r"\bfabric\b"]),
    ("synapse", [r"\bsynapse\b", r"azure synapse"]),
    ("redshift", [r"\bredshift\b"]),
    ("bigquery", [r"\bbigquery\b", r"big query"]),
    ("postgresql", [r"postgres", r"postgresql"]),
    ("mysql", [r"\bmysql\b"]),
    ("sql server", [r"sql server", r"\bmssql\b"]),
    ("oracle", [r"\boracle\b"]),
    ("mongodb", [r"\bmongodb\b", r"\bmongo\b"]),
    ("api", [r"\bapi\b", r"\bapis\b", r"\brest\b", r"restful"]),
    ("microservices", [r"microservices"]),
    ("devops", [r"\bdevops\b"]),
    ("ssis", [r"\bssis\b"]),
    ("ssrs", [r"\bssrs\b"]),
    ("ssas", [r"\bssas\b"]),
    ("powershell", [r"powershell"]),
    ("change data capture", [r"change data capture", r"\bcdc\b"]),
    ("precisely", [r"\bprecisely\b"]),
    ("wherescape", [r"where[\s-]?scape", r"\bwherescape\b"]),
]
